#! /bin/sh
# /etc/init.d/picam

### BEGIN INIT INFO
# Provides:          picam
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start the iFlan at boot
# Description:       A simple script to start iFlan at boot
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Picam"
    # run application you want to start
    sh /home/pi/longibot-raspberry/start.sh
    ;;
  stop)
    echo "Stopping iFlan"
    # kill application you want to stop
    sh /home/pi/longibot-raspberry/stop.sh
    ;;
  *)
    echo "Usage: /etc/init.d/iflan {start|stop}"
    exit 1
    ;;
esac

exit 0
